export const sliderImages = [
  "./slider/blue-sofa.png",
  //   "./slider/desk.png",
  //   "./slider/sofa1.png",
];

// export const newArrival = [
//   {
//     id:0,
//     img: "./products/table/table3.png",
//     name: "Modern Chair",
//     price: "550.00",
//     category: "table",
//   },
//   {
//     id:1,
//     img: "./products/sofa/sofa2.jpg",
//     name: "Two piece Sofa Two piece Sofa Two piece ",
//     price: "450.00",
//     category: "sofa",
//   },
//   {
//     id:2,
//     img: "./products/sofa/sofa3.avif",
//     name: "White Sofa",
//     price: "720.00",
//     category: "sofa",
//   },
//   {
//     id:3,
//     img: "./products/sofa/blue-sofa.png",
//     name: "Blue Single Sofa",
//     price: "180.00",
//     category: "sofa",
//   },
//   {
//     id:4,
//     img: "./products/bed/bed1.avif",
//     name: "White modern bed",
//     price: "630.00",
//     category: "bed",
//   },
//   {
//     id:5,
//     img: "./products/bed/bed2.webp",
//     name: "Normal Bed grey & White",
//     price: "430.00",
//     category: "bed",
//   },
//   {
//     id:6,
//     img: "./products/bed/bed3.webp",
//     name: "Regular Bed",
//     price: "330.00",
//     category: "bed",
//   },
//   {
//     id:7,
//     img: "./products/bed/bed4.jpeg",
//     name: "Wooden bed",
//     price: "530.00",
//     category: "bed",
//   },
//   {
//     id:8,
//     img: "./products/light/light1.png",
//     name: "Lamp (light)",
//     price: "50.00",
//     category: "light",
//   },
//   {
//     id:9,
//     img: "./products/light/light2.png",
//     name: "Modern Hanging lamp",
//     price: "70.00",
//     category: "light",
//   },
//   {
//     id:10,
//     img: "./products/light/light3.png",
//     name: "Standing Lamp",
//     price: "120.00",
//     category: "light",
//   },
//   {
//     id:11,
//     img: "./products/table/table1.png",
//     name: "4 Capacity Chair",
//     price: "950.00",
//     category: "table",
//   },
//   {
//     id:12,
//     img: "./products/table/table3.png",
//     name: "Modern Chair",
//     price: "550.00",
//     category: "table",
//   },
//   {
//     id:13,
//     img: "./products/table/table2.jpg",
//     name: "Blue High Quality table",
//     price: "450.00",
//     category: "table",
//   },
  
//   {
//     id:14,
//     img: "./products/stool/chair2.avif",
//     name: "Modern Stylish Chair",
//     price: "170.00",
//     category: "chair",
//   },
//   {
//     id:15,
//     img: "./products/stool/chair3.avif",
//     name: "Normal Chair",
//     price: "150.00",
//     category: "chair",
//   },
//   {
//     id:16,
//     img: "./products/stool/stool.jpg",
//     name: "Normal Chair",
//     price: "150.00",
//     category: "chair",
//   },
//   {
//     id:17,
//     img: "./products/sofa/sofa1.png",
//     name: "Orange Sofa",
//     price: "100.00",
//     category: "sofa",
//   },
// ];
